### ISSUE TITLE
Picker cannot load Emoji data

### ISSUE THREAD

**Issue by Serubin** [fireyy/vue-emoji-mart#4]
Picker is trying to load data from `localhost:8080/undefined`.

There appears to be a prop that shows up in the vue-devtools that doesn't show up in `master`: `dataUrl` which is `undefined` by default.

Where is this in the code and what should the default value be?

**Comment by fireyy** [comment]
Sorry, you can use the "version": "1.0.0", it works, you can install use `yarn add vue-emoji-mart@1.0.0` or `npm install vue-emoji-mart@1.0.0 --save`

I will fix the latest version soon.

**Comment by Serubin** [comment]
Using 1.0.0 I get the following:
```
Loading failed for the <script> with source “http://localhost:8080/0.vue-emoji-mart.js”.
Error: Loading chunk 0 failed.
```

**Comment by fireyy** [comment]
Sorry, I fix the issue, you can use the latest version now.

`dataUrl` now have default value 'http://unpkg.com/vue-emoji-mart/data/emoji.json'

**Comment by fireyy** [comment]
Also you can serve the `emoji.json` local.

**Comment by Serubin** [comment]
This is still pretty broken. This is how everything renders out.
<img width="309" alt="screen shot 2017-10-17 at 22 09 05" src="https://user-images.githubusercontent.com/1234465/31697830-f5b9741c-b387-11e7-8ae7-35641e38fab8.png">

**Comment by fireyy** [comment]
I see, you also need import the css, like

```
import 'vue-emoji-mart/css/emoji-mart.css'
import { Picker } from 'vue-emoji-mart'
```

**Comment by Serubin** [comment]
Thanks. Bit by bit. Still no emoji loading.
<img width="307" alt="screen shot 2017-10-17 at 22 35 34" src="https://user-images.githubusercontent.com/1234465/31698449-b1f38aca-b38b-11e7-9252-ab4a6271fe7d.png">

**Comment by fireyy** [comment]
If you use the Chrome，please check the network panel, if have request `http://unpkg.com/vue-emoji-mart...`

[Here have a demo](https://codesandbox.io/s/3yo6j0op1q)

**Comment by Serubin** [comment]
Okay, I see the issue. If you don't include the `native` option it wont populate...

**Comment by fireyy** [comment]
Yes, the file size is so large, I remove the `has_img` key in the `emoji.json`, so only `native ` is support.

**Comment by Serubin** [comment]
Wait - can we re-open this issue, it hasn't been resolved. If trying to maintain the original functionality - can use of the original emoji-mart be supported?

**Comment by fireyy** [comment]
#5

**Comment by fireyy** [comment]
f8116f461dccc1de031d650164e92876f7e5b619 1.0.5 fix this
