### ISSUE TITLE
how to render emoji in contenteditable div ?

### ISSUE THREAD

**Issue by Rahulkukadiya** [fireyy/vue-emoji-mart#7]
if i select the emoji and push inside the contenteditable div than it consider as normal sting and display
 like `<emoji emoji=":" :size="20"></emoji>`

**Comment by fireyy** [comment]
if you use native emoji, you can simple do:

```
methods: {
  insertSymbol (emoji) {
    this.$refs.editor.innerHTML += emoji.native
  }
}
```

[Here is a working demo](https://codesandbox.io/s/q306wvzl1w)

**Comment by Rahulkukadiya** [comment]
actually i use contenteditable div as my message editor so its works fine .but while i render this message in another component i need it with original emoji not native emoji. so is any other way to render original emoji ?

**Comment by fireyy** [comment]
This plugin does not export `emoji` component now, I think you may try another vue fork([emoji-mart-vue](https://github.com/jm-david/emoji-mart-vue)), sorry about that.
